# Generated by Django 4.1.4 on 2022-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
