# Generated by Django 4.1.4 on 2022-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appuser_age_alter_appuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=6, null=True),
        ),
    ]
